# Site settings
title: Pepper-Box, a Kafka Load Generator
tag_text: Pepper-Box
description: Pepper-Box is kafka load generator plugin for jmeter. It allows to send kafka messages of type plain text(JSON, XML, CSV or any other custom format) as well as java serialized objects.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
